default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost

development:
  <<: *default
  database: hello_rails_react_development
  username: postgres
  password: munana@1998
test:
  <<: *default
  database: hello_rails_react_test
  username: postgres
  password: munana@1998
production:
  <<: *default
  database: 
